version: "2.4"
services:
  remote-interpreter:
    build:
      context: .
      dockerfile: DockerfileForDev
    env_file: .env.development
    ports:
      - "8080:3000"
    depends_on:
      - db
      - word-suggestion
    volumes:
      - .:/app
  app:
    build:
      context: .
      dockerfile: DockerfileForDev
    env_file: .env.development
    ports:
      - "8000:3000"
    depends_on:
      - db
      - word-suggestion
    volumes:
      - .:/app
    command:
      [
          "./scripts/wait-for-it.sh",
          "db:5432",
          "-t",
          "120",
          "--",
          "./scripts/wait-for-it.sh",
          "word-suggestion:8080",
          "-t",
          "120",
          "--",
          "./scripts/start-development.sh",
      ]
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: postgres_app_user
      POSTGRES_PASSWORD: postgres_password_app_user
    ports:
      - 5432:5432
  word-suggestion:
    image: willianantunes/runner-said-no-one-ever
    environment:
      - PUMA_BIND_ADDRESS=0.0.0.0
      - PUMA_BIND_PORT=8080
      - PUMA_MIN_THREADS=4
      - PUMA_MAX_THREADS=20
      - PUMA_NUMBER_OF_WORKERS=0
      - PUMA_PERSISTENT_TIMEOUT=20
      - PUMA_FIRST_DATA_TIMEOUT=30
      - RACK_ENV=development
      - APP_ENV=development
      - PROJECT_LOG_LEVEL=DEBUG
      - RACK_IP_ADDRESS_HEADER=REMOTE_ADDR
    ports:
      - "8081:8080"
  tests:
    build:
      context: .
      dockerfile: DockerfileForDev
    working_dir: /app
    env_file: .env.test
    volumes:
      - .:/app
    depends_on:
      - db
      - word-suggestion
    command:
      [
          "./scripts/wait-for-it.sh",
          "db:5432",
          "-t",
          "120",
          "--",
          "./scripts/wait-for-it.sh",
          "word-suggestion:8080",
          "-t",
          "120",
          "--",
          "./scripts/start-tests.sh",
      ]
