version: "2.4"
services:
  word-suggestion:
    image: willianantunes/runner-said-no-one-ever
    environment:
      - PUMA_BIND_ADDRESS=0.0.0.0
      - PUMA_BIND_PORT=8080
      - PUMA_MIN_THREADS=4
      - PUMA_MAX_THREADS=20
      - PUMA_NUMBER_OF_WORKERS=0
      - PUMA_PERSISTENT_TIMEOUT=20
      - PUMA_FIRST_DATA_TIMEOUT=30
      - RACK_ENV=development
      - APP_ENV=development
      - PROJECT_LOG_LEVEL=DEBUG
      - RACK_IP_ADDRESS_HEADER=REMOTE_ADDR
    ports:
      - "8081:8080"
